var projects = [
    {long_name: "One-shot and few-shot learning of word embeddings",
     name: "One-shot words",
     url: "https://arxiv.org/pdf/1710.10280.pdf",
     attributes: ["Few-shot", "Language", "Memory"]},
    {long_name: "An analytic theory of generalization dynamics and transfer learning in deep linear networks",
     name: "Generalization dynamics",
     url: "https://arxiv.org/pdf/1809.10374.pdf",
     attributes: ["Generalization", "Theory", "Transfer"]},
    {long_name: "Building on prior knowledge without building it in",
     name: "Without building it in",
     url: "https://www.cambridge.org/core/journals/behavioral-and-brain-sciences/article/building-on-prior-knowledge-without-building-it-in/F342A14C57094D5AF7BC62950AE49CD8",
     attributes: ["Generalization", "Transfer", "Cognition"]},
    {long_name: "Emergent systematic generalization in a situated agent",
     name: "Embodiment & generalization",
     url: "https://arxiv.org/pdf/1910.00571.pdf",
     attributes: ["Generalization", "Transfer", "Zero-shot", "Language", "RL"]},
    {long_name: "Zero-shot task adaptation by homoiconic meta-mapping",
     name: "Zero-shot HoMM",
     url: "https://arxiv.org/pdf/1905.09950.pdf",
     attributes: ["Zero-shot", "Transfer", "Cognition"]},
    {long_name: "Automated curricula through setter-solver interactions",
     name: "RL auto-curricula",
     url: "https://arxiv.org/pdf/1909.12892.pdf",
     attributes: ["Curricula", "Generative", "RL"]},
    {long_name: "Analogies emerge from learning dynamics in neural networks",
     name: "Analogy dynamics",
     url: "https://mindmodeling.org/cogsci2017/papers/0477/paper0477.pdf",
     attributes: ["Transfer", "Cognition", "Theory"]},
    {long_name: "SWIL",
     name: "SWIL",
     url: "",
     attributes: ["Cognition", "Memory"]},
    {long_name: "Different presentations of a mathematical concept can support learning in complementary ways",
     name: "Math presentations",
     url: "http://web.stanford.edu/~lampinen/papers/Lampinen_McClelland_2017_PrePrint.pdf",
     attributes: ["Curricula", "Cognition"]},
    {long_name: "Improving image generative models with human interactions",
     name: "GANs + humans",
     url: "https://arxiv.org/pdf/1709.10459.pdf",
     attributes: ["Generative"]},
    {long_name: "Improving the replicability of psychological science through pedagogy",
     name: "Psych. replicability",
     url: "https://journals.sagepub.com/doi/pdf/10.1177/2515245917740427",
     attributes: ["Cognition"]},
];

