var projects = [
    {name: "One-shot and few-shot learning of word embeddings",
     attributes: ["Few-shot", "Language", "Memory"]},
    {name: "An analytic theory of generalization dynamics and transfer learning in deep linear networks",
     attributes: ["Generalization", "Theory", "Transfer"]},
    {name: "Building on prior knowledge without building it in",
     attributes: ["Generalization", "Transfer", "Cognition"]},
    {name: "Emergent systematic generalization in a situated agent",
     attributes: ["Generalization", "Transfer", "Zero-shot", "Language", "RL"]},
    {name: "Zero-shot task adaptation by homoiconic meta-mapping",
     attributes: ["Zero-shot", "Transfer", "Cognition"]},
    {name: "Automated curricula through setter-solver interactions",
     attributes: ["Curricula", "Generative", "RL"]},
    {name: "Improving image generative models with human interactions",
     attributes: ["Generative"]},
    {name: "Analogies emerge from learning dynamics",
     attributes: ["Generative"]},
    {name: "Different presentations of a mathematical concept can support learning in complementary ways",
     attributes: ["Curricula", "Cognition"]},
    {name: "Improving the replicability of psychological science through pedagogy",
     attributes: ["Cognition"]},
    {name: "SWIL",
     attributes: ["Cognition", "Memory"]},
];

