var projects = [
    {long_name: "One-shot and few-shot learning of word embeddings",
     name: "Jabberwocky",
     attributes: ["Few-shot", "Language", "Memory"]},
    {long_name: "An analytic theory of generalization dynamics and transfer learning in deep linear networks",
     name: "Generalization dynamics",
     attributes: ["Generalization", "Theory", "Transfer"]},
    {long_name: "Building on prior knowledge without building it in",
     name: "Without building it in",
     attributes: ["Generalization", "Transfer", "Cognition"]},
    {long_name: "Emergent systematic generalization in a situated agent",
     name: "Embodiment",
     attributes: ["Generalization", "Transfer", "Zero-shot", "Language", "RL"]},
    {long_name: "Zero-shot task adaptation by homoiconic meta-mapping",
     name: "Zero-shot HoMM",
     attributes: ["Zero-shot", "Transfer", "Cognition"]},
    {long_name: "Automated curricula through setter-solver interactions",
     name: "Auto-curricula",
     attributes: ["Curricula", "Generative", "RL"]},
    {long_name: "Analogies emerge from learning dynamics in neural networks",
     name: "Analogy dynamics",
     attributes: ["Transfer", "Cognition", "Theory"]},
    {long_name: "SWIL",
     name: "SWIL",
     attributes: ["Cognition", "Memory"]},
    {long_name: "Different presentations of a mathematical concept can support learning in complementary ways",
     name: "Math presentations",
     attributes: ["Curricula", "Cognition"]},
    {long_name: "Improving image generative models with human interactions",
     name: "GANs w/ humans",
     attributes: ["Generative"]},
    {long_name: "Improving the replicability of psychological science through pedagogy",
     name: "Psych. replicability",
     attributes: ["Cognition"]},
];

